# -*- mode: ruby -*-
# vi: set ft=ruby :

def isLinux()
    RUBY_PLATFORM.include? "linux"
end

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  config.vm.network "forwarded_port", guest: 8090, host: 8090
  config.vm.network "forwarded_port", guest:8001, host:8001
   config.vm.network "forwarded_port", guest:9090, host:9090
  config.vm.network "forwarded_port", guest:3000, host:3000
  config.vm.synced_folder isLinux ? "~/Documents/data": "#{Dir.home}\\Documents\\data", "/home/vagrant/data"
  config.vm.provision "file", source: isLinux ? "~/.ssh/id_rsa":"#{Dir.home}\\.ssh\\id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: isLinux ? "~/.aws" :"#{Dir.home}\\.aws", destination: "/home/vagrant/.aws"
  config.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install software-properties-common -y
      apt-add-repository --yes --update ppa:ansible/ansible
      apt install ansible -y
      apt install -y python3-pip
      apt install build-essential libssl-dev libffi-dev python3-dev
   SHELL
   config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/devops.yml"
  end
end
