# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "~/Documents/data", "/home/vagrant/data"
  config.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install software-properties-common -y
      apt-add-repository --yes --update ppa:ansible/ansible
      apt install ansible -y
   SHELL
   config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/devops.yml"
  end
end
