# -*- mode: ruby -*-
# vi: set ft=ruby :

def isLinux()
    RUBY_PLATFORM.include? "linux"
end

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder isLinux ? "~/Documents/data": "#{Dir.home}\\Documents\\data", "/home/vagrant/data"
  config.vm.provision "file", source: isLinux ? "~/.ssh/id_rsa":"#{Dir.home}\\.ssh\\id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: isLinux ? "~/.aws" :"#{Dir.home}\\.aws, destination: "/home/vagrant/.aws"
  config.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install software-properties-common -y
      apt-add-repository --yes --update ppa:ansible/ansible
      apt install ansible -y
   SHELL
   config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/devops.yml"
  end
end
