---
# tasks file for base
- name: "Update cache"
  become: true
  apt:
    cache_valid_time: "{{ base_cache_valid_time | int }}"
    update_cache: true

- name: "install python-apt"
  become: true
  command: "apt-get install python-apt -y"

- name: "install pip"
  become: true
  apt:
    name: python3-pip

- name: "install awscli"
  command: "pip3 install awscli --upgrade --user"

#- name: "update bashrc"
#  lineinfile:
#    path: "/home/vagrant/.bashrc"
#    line: "export PATH=\"$PATH:~/.local/bin/\""

#- name: "reload bashrc"
#  command: "source /home/vagrant/.bashrc"
