# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "~/Documents/data", "/home/vagrant/data"
  config.vm.provision "shell", inline: <<-SHELL

  SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/docker.yml"
  end
end
