# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "~/Documents/data", "/home/vagrant/data"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", inline: <<-SHELL
      apt update
      apt upgrade -y
      apt install -y python3-pip
      apt install build-essential libssl-dev libffi-dev python3-dev
      apt install -y python3-venv
   SHELL
end
