# -*- mode: ruby -*-
# vi: set ft=ruby :

def isLinux()
    RUBY_PLATFORM.include? "linux"
end

Vagrant.configure("2") do |config|
#   config.vm.network "forwarded_port", guest:9090, host:9090 
#      config.vm.network "forwarded_port", guest:8080, host:8080 
#      config.vm.network "forwarded_port", guest:80, host:80 
#      config.vm.network "forwarded_port", guest:3000, host:3000 
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder isLinux ? "~/Documents/data": "#{Dir.home}\\Documents\\data", "/home/vagrant/data"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", inline: <<-SHELL
      apt update
      apt upgrade -y
      apt install -y python3-pip
      apt install build-essential libssl-dev libffi-dev python3-dev 
      apt install -y python3-venv
   SHELL
end
