

- name: "Download and install composer"
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ composer_version }}/docker-compose-{{ composer_os}}-{{ composer_arq }}
    dest: /usr/local/bin/docker-compose
    mode: "+x"
